import arc.files.*
import arc.struct.*
import arc.util.io.*

sourceSets.main.java.srcDirs = ['src/']

dependencies{
    implementation project(':main')
    compileOnly project(':annotations')
    annotationProcessor project(':annotations')
    implementation "com.github.Anuken.Arc:arc-core:$arcVersion"
    implementation "com.github.Anuken.Mindustry:core:$mindustryVersion"
}

tasks.register('proc', JavaExec){
    dependsOn classes
    inputs.dir file('../main/assets-raw/sprites')
    outputs.dir file('../main/assets/sprites')

    workingDir = rootProject.ext.assetsDir
    mainClass = (rootProject.ext.modName as String).replace("-", "") + '.tools.Tools'
    classpath = sourceSets.main.runtimeClasspath
    systemProperty 'currentModName', rootProject.ext.modName

    doFirst{
        delete outputs.files
        copy{
            from inputs.files
            into outputs.files.singleFile
        }
    }
}

tasks.register('updateBundles'){
    doLast{
        def uniEscape = { String s ->
            s.collect{ char c ->
                (c > 61 && c < 127) ? (c == '\\' as char ? "\\\\" : c) :
                (c >= 0xE000 && c <= 0xF8FF) ? String.format("\\u%04x", (int) c) : c
            }.join()
        }

        File bundlesDir = file("${rootProject.ext.assetsDir}/bundles")
        File baseBundleFile = file("$bundlesDir/bundle.properties")
        if(!baseBundleFile.exists()) return

        OrderedMap<String, String> base = new OrderedMap<>()
        PropertiesUtils.load(base, Fi.get(baseBundleFile.path).reader())

        IntMap<String> comments = new IntMap<>()
        def lines = Fi.get(baseBundleFile.path).reader().readLines()
        int offset = 0
        for(int i = 0; i < lines.size(); i++){
            def line = lines.get(i)
            if(i > 0 && lines.get(i - 1).endsWith("\\")) offset++
            else if(line.isEmpty() || line.startsWith("#")) comments.put(i - offset, line)
        }

        Fi.get(bundlesDir.path).walk{ child ->
            if(child.name() == "bundle.properties" || child.toString().contains("output")) return
            if(project.hasProperty("bundle") && child.name() != project.property("bundle")) return

            OrderedMap<String, String> other = new OrderedMap<>()
            PropertiesUtils.load(other, child.reader())

            for(String key : other.orderedKeys().toSeq()){
                if(!base.containsKey(key)) other.remove(key)
            }
            for(String key : base.orderedKeys()){
                if(other.get(key) == null || other.get(key).trim().isEmpty()) other.put(key, base.get(key))
            }

            StringBuilder result = new StringBuilder()
            int i = 0
            for(String key : base.orderedKeys()){
                while(comments.containsKey(i++)) result.append(comments.get(i - 1)).append('\n')
                if(other.get(key) == null) continue
                def v = other.get(key)
                result.append(key).append(" =").append(v.trim().isEmpty() ? "" : " ").append(uniEscape(v).replace("\n", "\\n")).append('\n')
            }
            child.writeString(result.toString())
        }
    }
}
