name: Java CI

on: [push]

jobs:
  buildJar:
    name: Build and Publish Jar
    runs-on: ubuntu-latest
    permissions:
      contents: write # for Update bundles

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Update bundles
        run: |
           ./gradlew updateBundles

           if [ -n "$(git status --porcelain)" ]; then
             git config --global user.name "Github Actions"
             git config --global user.email "actions@github.com"
             git add main/assets/bundles/*
             git commit -m "Automatic bundle update"
               git push
             fi

      - name: Build mod artifact
        run: |
          chmod +x gradlew
          ./gradlew main:deploy main:dex tools:proc

      - name: Upload built mod artifact as a GitHub Action artifact
        uses: actions/upload-artifact@v4
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        with:
          name: Template (in a box)
          path: main/build/libs/Template.jar
          if-no-files-found: error
          compression-level: 0

      - name: Upload built mod artifact into release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release' && github.event.action == 'created'
        with:
          files: build/libs/Template.jar