name: Java CI

on: [push, release]

jobs:
  buildJar:
    name: Build and Publish Jar
    runs-on: ubuntu-latest
    permissions:
      contents: write # for Update bundles and creating releases

    steps:
      - uses: actions/checkout@v4

      - name: Get Mod Display Name for Artifacts
        id: mod_details
        run: |
          raw_display_name=$(jq -r '.displayName' mod.json)
          mod_file_name=$(echo "$raw_display_name" | tr -d ' ')
          echo "MOD_FILE_NAME=${mod_file_name}" >> $GITHUB_ENV
          echo "mod_file_name_output=${mod_file_name}" >> $GITHUB_OUTPUT
          echo "Mod file name set to: ${mod_file_name}"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK Platform 33 and Build Tools
        run: |
          yes | sdkmanager --licenses > /dev/null || true
          sdkmanager "platforms;android-33" "build-tools;33.0.2"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Update bundles
        run: |
          ./gradlew updateBundles
          
          if [ -n "$(git status --porcelain main/assets/bundles)" ]; then
            git config --global user.name "Github Actions"
            git config --global user.email "actions@github.com"
            git add main/assets/bundles/*
            git commit -m "Automatic bundle update"
            git push
          else
            echo "No bundle changes to commit."
          fi

      - name: Build mod artifacts (Desktop, Android, Process Assets)
        run: |
          chmod +x gradlew
          ./gradlew tools:proc main:deploy main:dex

      - name: Upload built mod artifact (Android/Cross-platform)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MOD_FILE_NAME }} (Android)
          path: main/build/libs/${{ env.MOD_FILE_NAME }}.jar
          if-no-files-found: error
          compression-level: 0

      - name: Upload built mod artifact (Desktop)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MOD_FILE_NAME }} (Desktop)
          path: main/build/libs/${{ env.MOD_FILE_NAME }}Desktop.jar
          if-no-files-found: error
          compression-level: 0

      - name: Upload built mod artifact into release (Android/Cross-platform)
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release' && github.event.action == 'created'
        with:
          files: main/build/libs/${{ steps.mod_details.outputs.mod_file_name_output }}.jar