name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for Update bundles

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: 33.0.2
          target: default

      - name: Install Android SDK Platform 33
        run: |
          sdkmanager "platforms;android-33" "build-tools;33.0.2"

      - name: Check Android SDK Installation
        run: ls -la $ANDROID_SDK_ROOT/platforms/android-33

      - name: Update bundles
        if: ${{ github.repository == 'stabu-dev/MindustryJavaModTemplate' }}
        run: |
           ./gradlew updateBundles

           if [ -n "$(git status --porcelain)" ]; then
             git config --global user.name "Github Actions"
             git config --global user.email "actions@github.com"
             git add main/assets/bundles/*
             git commit -m "Automatic bundle update"
               git push
             fi

      - name: Build and dexify mod jar file
        run: |
          chmod +x gradlew
          ./gradlew main:deploy main:dex tools:proc --info

      - name: Upload built mod jar file
        uses: actions/upload-artifact@v4
        with:
          name: Template (zipped)
          path: main/build/libs/Template.jar